### ISSUE TITLE
GapChargeTransport_tool.cc fails to compile with gcc@12.5.0

### ISSUE THREAD

**Issue by gartung** [DUNE/dunesim#111]
The error is shown below. The base class GetOffset function has float as the last argument while the derived class GerOffset function has int as the last argument.  In gcc@12.5.0 override checks are strict.

```
  In file included from /tmp/jenkins/spack-stage/spack-stage-dunesim-develop-bs26l4xlr5omadovndozt2vd3f2l2xbg/spack-src/dunesim/GapChargeTransport/GapChargeTransport_tool.cc:3:
> /tmp/jenkins/spack-stage/spack-stage-dunesim-develop-bs26l4xlr5omadovndozt2vd3f2l2xbg/spack-src/dunesim/GapChargeTransport/GapChargeTransport.hh:17:34: error: 'std::pair<ROOT::Math::PositionVector3D
<ROOT::Math::Cartesian3D<double>, ROOT::Math::GlobalCoordinateSystemTag>, int> gap::GapChargeTransport::GetOffset(double, double, double, int) const' marked 'override', but does not override
     17 |     std::pair<geo::Point_t, int> GetOffset(double x, double y, double z, int n) const override;
        |                                  ^~~~~~~~~
  In file included from /scratch/workspace/build-spack-env/label1/gcc-11/spack_env/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-x86_64_v2/gcc-12.5.0-yzmbnxfxx7o7lwrjbkbj
qo7p2nbu6frs/lib/gcc/x86_64-pc-linux-gnu/12.5.0/../../../../include/c++/12.5.0/memory:75,
                   from /scratch/workspace/build-spack-env/label1/gcc-11/spack_env/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-x86_64_v3/cetlib-3.18.02-znebzvqa7rprpapd
4zmri5xjjjqhtmmv/include/cetlib/filepath_maker.h:28,
                   from /scratch/workspace/build-spack-env/label1/gcc-11/spack_env/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-x86_64_v3/fhicl-cpp-4.18.04-i3xiahbl3jkxd
t2bl25cpdzvsep3ngpd/include/fhiclcpp/parse.h:10,
                   from /scratch/workspace/build-spack-env/label1/gcc-11/spack_env/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-x86_64_v3/fhicl-cpp-4.18.04-i3xiahbl3jkxd
t2bl25cpdzvsep3ngpd/include/fhiclcpp/coding.h:29,
                   from /scratch/workspace/build-spack-env/label1/gcc-11/spack_env/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-x86_64_v3/fhicl-cpp-4.18.04-i3xiahbl3jkxd
t2bl25cpdzvsep3ngpd/include/fhiclcpp/ParameterSet.h:12,
                   from /scratch/workspace/build-spack-env/label1/gcc-11/spack_env/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-x86_64_v3/art-3.14.04-ggfawku2zpv6arwsqtx
2yrkusei72t53/include/art/Utilities/ToolMacros.h:19,
                   from /tmp/jenkins/spack-stage/spack-stage-dunesim-develop-bs26l4xlr5omadovndozt2vd3f2l2xbg/spack-src/dunesim/GapChargeTransport/GapChargeTransport_tool.cc:1:
  /scratch/workspace/build-spack-env/label1/gcc-11/spack_env/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-x86_64_v2/gcc-12.5.0-yzmbnxfxx7o7lwrjbkbjqo7p2nbu6frs/lib/gcc/x
86_64-pc-linux-gnu/12.5.0/../../../../include/c++/12.5.0/bits/unique_ptr.h: In instantiation of 'std::__detail::__unique_ptr_t<_Tp> std::make_unique(_Args&& ...) [with _Tp = gap::GapChargeTransport; _
Args = {const fhicl::ParameterSet&}; __detail::__unique_ptr_t<_Tp> = __detail::__unique_ptr_t<gap::GapChargeTransport>]':
  /tmp/jenkins/spack-stage/spack-stage-dunesim-develop-bs26l4xlr5omadovndozt2vd3f2l2xbg/spack-src/dunesim/GapChargeTransport/GapChargeTransport_tool.cc:247:1:   required from here
> /scratch/workspace/build-spack-env/label1/gcc-11/spack_env/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-x86_64_v2/gcc-12.5.0-yzmbnxfxx7o7lwrjbkbjqo7p2nbu6frs/lib/gcc/x
86_64-pc-linux-gnu/12.5.0/../../../../include/c++/12.5.0/bits/unique_ptr.h:1072:30: error: invalid new-expression of abstract class type 'gap::GapChargeTransport'
   1072 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
        |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /tmp/jenkins/spack-stage/spack-stage-dunesim-develop-bs26l4xlr5omadovndozt2vd3f2l2xbg/spack-src/dunesim/GapChargeTransport/GapChargeTransport.hh:13:9: note:   because the following virtual functions
 are pure within 'gap::GapChargeTransport':
     13 |   class GapChargeTransport : public gap::IGapChargeTransport {
        |         ^~~~~~~~~~~~~~~~~~
  In file included from /tmp/jenkins/spack-stage/spack-stage-dunesim-develop-bs26l4xlr5omadovndozt2vd3f2l2xbg/spack-src/dunesim/GapChargeTransport/GapChargeTransport.hh:10:
> /scratch/workspace/build-spack-env/label1/gcc-11/spack_env/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-x86_64_v3/larsim-10.21.00-szmvqvffl5mvvqwns72cxf6j4p4pth3c/incl
ude/larsim/IonizationScintillation/IGapChargeTransport.hh:13:44: note:     'virtual std::pair<ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<double>, ROOT::Math::GlobalCoordinateSystemTag>, floa
t> gap::IGapChargeTransport::GetOffset(double, double, double, float) const'
     13 |     virtual std::pair<geo::Point_t, float> GetOffset(double x,
        |                                            ^~~~~~~~~
> /scratch/workspace/build-spack-env/label1/gcc-11/spack_env/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spa/linux-x86_64_v3/larsim-10.21.00-szmvqvffl5mvvqwns72cxf6j4p4pth3c/incl
ude/larsim/IonizationScintillation/IGapChargeTransport.hh:20:20: note:     'virtual double gap::IGapChargeTransport::MaxGap() const'
     20 |     virtual double MaxGap() const = 0;
        |                    ^~~~~~
```

**Comment by gartung** [comment]
@tomjunk

**Comment by gartung** [comment]
The const override definition of GetOffset in dunesim https://github.com/DUNE/dunesim/blob/0a673fcff0f04e9a57b90c14eb5e09f0fa5cbfbf/dunesim/GapChargeTransport/GapChargeTransport.hh#L17  uses int as the last argument.

**Comment by gartung** [comment]
The base class definition of [GetOffset in larsim](https://github.com/LArSoft/larsim/blob/8ab8dadf92c4d7b3552f7b894ace0a304e2859b2/larsim/IonizationScintillation/IGapChargeTransport.hh#L13) uses float as the last argument.

**Comment by gartung** [comment]
The compiler error happens because your function signatures do not match.In your base class IGapChargeTransport, the pure virtual function uses float for the count of electrons and its return pair. In your derived class GapChargeTransport, you used int instead. Because the data types are different, the compiler treats your derived function as a completely new function rather than an override, leaving the pure virtual base function unimplemented.The FixChange the data types in your GapChargeTransport class declaration from int to float to perfectly match the base class.cpp
```
class GapChargeTransport : public gap::IGapChargeTransport {
  public:
    explicit GapChargeTransport(fhicl::ParameterSet const& pset);

    // Change 'int' to 'float' here:
    std::pair<geo::Point_t, float> GetOffset(double x, double y, double z, float n) const override;
};
```
Use code with caution.
Why GCC 12 Caught ThisBecause you correctly used the override keyword, GCC 12 immediately flags this as a compilation error. It notices that GapChargeTransport::GetOffset with an int doesn't actually override any virtual function in the base class, helping you catch the signature mismatch before it causes trickier linker or runtime bugs.

**Comment by gartung** [comment]
This compiles and I think it has the intended meaning.

```
 git diff
diff --git a/dunesim/GapChargeTransport/GapChargeTransport.hh b/dunesim/GapChargeTransport/GapChargeTransport.hh
index ba61e20..8f22bde 100644
--- a/dunesim/GapChargeTransport/GapChargeTransport.hh
+++ b/dunesim/GapChargeTransport/GapChargeTransport.hh
@@ -14,8 +14,8 @@ namespace gap {
   public:
     explicit GapChargeTransport(fhicl::ParameterSet const& pset);
 
-    std::pair<geo::Point_t, int> GetOffset(double x, double y, double z, int n) const override;
-
+    std::pair<geo::Point_t, float> GetOffset(double x, double y, double z, float n) const override;
+    double MaxGap() const override;
     std::string fp4_volume;
     std::string Volume() const override;
 
diff --git a/dunesim/GapChargeTransport/GapChargeTransport_tool.cc b/dunesim/GapChargeTransport/GapChargeTransport_tool.cc
index 110a898..4c02573 100644
--- a/dunesim/GapChargeTransport/GapChargeTransport_tool.cc
+++ b/dunesim/GapChargeTransport/GapChargeTransport_tool.cc
@@ -198,17 +198,17 @@ namespace gap {
   }
 
   // the main function - here the new postion and the new charge are defined, this is called inside the IonAndScint module
-  std::pair<geo::Point_t, int> GapChargeTransport::GetOffset(double x,
+  std::pair<geo::Point_t, float> GapChargeTransport::GetOffset(double x,
                                                              double y,
                                                              double z,
-                                                             int n_el) const
+                                                             float n_el) const
   {
     mf::LogInfo("GapChargeTransport")
       << "Calculation Initialized, x =" << x << ", y = " << y << ", z = ";
-    mf::LogInfo("GapChargeTransport") << "nelectrons = " << n_el;
+    mf::LogInfo("GapChargeTransport") << "nelectrons = " << round(n_el);
     GapInfo the_gap = Gap(x, y, z);
     double probability = ComputeShiftProbability(the_gap, x, y, z);
-    int n = round(probability * n_el);
+    float n = round(probability * n_el);
     double shifted_x, shifted_y, shifted_z;
     shifted_x = x;
     shifted_y = y;
@@ -235,6 +235,8 @@ namespace gap {
     return std::make_pair(geo::Point_t(shifted_x, shifted_y, shifted_z), n);
   }
 
+  double GapChargeTransport::MaxGap() const {return 0.0;}
+
   //return volume name and throw exception in case there is a typo in the name (in .fcl)
   std::string GapChargeTransport::Volume() const
   {
```

**Comment by gartung** [comment]
@tomjunk The base class `gap::IGapChargeTransport` was changed between larsim 10.20.06 and larsim 10.21.00. This change will be needed when DUNE moves to larsoft 10.24.00.
